title: tardate 2025
email: gallagher.paul@gmail.com
author: Paul Gallagher
description: > #
  This blog is my occasional diary of Quite Interesting Things.
  It is generally technical, meaning all things web, open source, polyglot-programming, electronics and concerning data.
  But sometimes ravings on books or musics, and occasionally a rant or philosophical dribble.
baseurl:     ""
url:         "https://blog.tardate.com"
date_format: "%b %-d, %Y"
feed_path: "/feed.xml"

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: UA-4894631-1
google_tag_manager:

google_ad_client: "ca-pub-8429465058616611"
google_ad_slot: "1715866040"

# Bing services
bing_verification:

# Optional features
animated:             true
show_related_posts:   false
show_post_footers:    false
show_social_icons:    true
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: false

# Facebook Page integration
# (for instant articles and other stuff)
fb_page: false
fb_page_id:

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: tardate

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username:  tardate
bitbucket_username:
stackoverflow_id: 6329
mastodon_url: "https://ruby.social/@tardate"
mastodon_name: "@tardate@ruby.social"
instagram_username: "little.electronic.art.projects"
twitter_username: tardate
linkedin_username: gallagherpaul
medium_id:
bitcoin_url:
paypal_url:
flattr_button:
bluesky_id: tardate.bsky.social
qrz_id: 9V1DI

# Post sharing icons
show_sharing_icons: true
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Share this post!'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'Email Address'
    content:  'What would you like to say?'
    subject:  'New submission!'
    submit:   'Say Hello'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting us. We will reply as soon as possible.'
  og_locale: 'en_US'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    /:categories/:year/:month/:title.html
paginate:     4
sass:
  compressed: true
plugins:
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - bin
  - vendor
  - Gemfile
  - Gemfile.lock
